### ISSUE TITLE
你的蓝牙项目弄出来了吗

### ISSUE THREAD

**Issue by MarkTsy** [fjasmin/MyStudyNote#1]

**Comment by fjasmin** [comment]
你是？我都从原公司离职。现在开始找工作

**Comment by MarkTsy** [comment]
看到一个 你在蓝牙项目上的 issue， 你也在弄蓝牙相关的项目吧， 如果想请教一下项目上的问题

**Comment by fjasmin** [comment]
什么项目。能给下链接吗？

**Comment by MarkTsy** [comment]
项目找不到了 一个关于 蓝牙电话相关的

**Comment by MarkTsy** [comment]
https://github.com/TangZhiDe/BtPhone

**Comment by fjasmin** [comment]
请问有什么问题，对于这个项目？

**Comment by fjasmin** [comment]
问题我是解决了。但是这个项目需要对象android 9的机器。我现在不知道怎么回答你。你现在用什么系统来编辑这个软件？

**Comment by MarkTsy** [comment]
我是as做app层开发， 一些蓝牙的api都是hide的， 获取不到， 要是系统级开发的话方便很多， 你这边是系统应用开发吗

**Comment by fjasmin** [comment]
我也是跟你一样，开始是app层的开发，被逼着看源码，framework层的代码。我给你一个链接，里面有所有蓝牙设备的源码，你可以看看。https://www.androidos.net.cn/android/9.0.0_r8/xref/packages/apps/Car/Dialer/src/com/android/car/dialer/ui。这个是基于android9的蓝牙电话的全部源代码。看完就通了

**Comment by MarkTsy** [comment]
哦哦 thks， 我看一下

**Comment by MarkTsy** [comment]
项目ok了， 感谢！ 需要framework层的支持才会开放 蓝牙电话的协议。
